### ISSUE TITLE
``dtool readme`` command outputs stack trace when called on frozen dataset

### ISSUE THREAD

**Issue by tjelvar-olsson** [jic-dtool/dtool-create#1]
The ``dtool readme`` command results in stack trace when called on a frozen dataset.
It needs to have some sanity checking that the dataset provided is a proto dataset.

Example output below:

```
$ dtool readme interactive symlink:///Users/olssont/junk/my_dataset
Traceback (most recent call last):
  File "/Users/olssont/envs/dtool/bin/dtool", line 11, in <module>
    sys.exit(dtool())
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/dtool_create/dataset.py", line 154, in interactive
    config_path=CONFIG_PATH)
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/dtoolcore/__init__.py", line 318, in from_uri
    return cls._from_uri_with_typecheck(uri, config_path, "protodataset")
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/dtoolcore/__init__.py", line 164, in _from_uri_with_typecheck
    "{} is not a {}".format(uri, cls.__name__))
dtoolcore.DtoolCoreTypeError: symlink:///Users/olssont/junk/my_dataset is not a ProtoDataSet
```

**Comment by tjelvar-olsson** [comment]
Fixed in 6ab583c
