### ISSUE TITLE
Python2 issue with unicode in readme

### ISSUE THREAD

**Issue by tjelvar-olsson** [jic-dtool/dtool-create#15]
```
$ dtool readme edit ~/junk/test-unicode-ds
Traceback (most recent call last):
  File "/Users/olssont/envs/dtool/bin/dtool", line 11, in <module>
    sys.exit(dtool())
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/dtool_create/dataset.py", line 278, in edit
    edited_content = click.edit(readme_content)
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/click/termui.py", line 456, in edit
    return editor.edit(text)
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/click/_termui_impl.py", line 425, in edit
    text = text.encode(encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
```

**Comment by tjelvar-olsson** [comment]
Fixed in 323ee1c
