### ISSUE TITLE
inconsistency between date and datetime objects

### ISSUE THREAD

**Issue by sannant** [jic-dtool/dtool-create#24]
Using dtool create, I had the error that datetime.date has no attribute date.

The bug is caused by the following lines:

https://github.com/jic-dtool/dtool-create/blob/80563dd4b05ec6434ece4abdc307eef611c26f5c/dtool_create/dataset.py#L89-L98

The default happens to be a date object, not a datetime object, but the parse_date function returns a datetime object. 

Here is the proposed fix:

```python
        elif isinstance(value, datetime.date):
            def parse_date(value):
                try:
                    date = datetime.datetime.strptime(value, "%Y-%m-%d")
                except ValueError as e:
                    raise click.BadParameter(
                        "Could not parse date, {}".format(e), param=value)
                return date.date()
            new_value = click.prompt(key, default=value, value_proc=parse_date)
            d[key] = new_value.isoformat()
```

This might be related to #22, since something has been changed from datetime to date.

I wonder why this error comes up now, since the code dates from may.

Current python version is 3.8.

**Comment by tjelvar-olsson** [comment]
Hi Antoine,

Could you send me the exact command you ran and the full error that you got?
Could you also please send me the output of running ``dtool --version`` on your system?

This will help me try to work out what is going on.

Best,
Tjelvar

**Comment by sannant** [comment]
Hi Tjelvar, 

here the dtool readme template:
```yml
---
creation_date: {date}
```
here the command that failed, after a successfull  `dtool create test`
```
dtool readme interactive test
creation_date [2021-01-25]: 
Traceback (most recent call last):
  File "/usr/local/bin/dtool", line 8, in <module>
    sys.exit(dtool())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dtool_create/dataset.py", line 259, in interactive
    descriptive_metadata = _prompt_for_values(descriptive_metadata)
  File "/usr/local/lib/python3.8/site-packages/dtool_create/dataset.py", line 98, in _prompt_for_values
    d[key] = new_value.date().isoformat()
AttributeError: 'datetime.date' object has no attribute 'date'
```


```
dtool --version
dtool, version 

Base:
dtoolcore, version 3.18.0
dtool-cli, version 0.7.0

Storage brokers:
file, dtoolcore, version 3.18.0
symlink, dtool-symlink, version 0.3.0
smb, dtool-smb, version 0.1.0
s3, dtool-s3, version 0.10.0
https, dtool-http, version 0.5.0
http, dtool-http, version 0.5.0
ecs, dtool-ecs, version 0.5.0

Plugins:
dtool-config, version 0.4.0
dtool-create, version 0.23.1
dtool-info, version 0.16.1
```

Thank you for the help, 

Best, 

Antoine Sanner

**Comment by tjelvar-olsson** [comment]
Thanks, I've managed to reproduce the issue. Will look into what is causing it now.

**Comment by tjelvar-olsson** [comment]
Fixed in b4d9ef7

**Comment by sannant** [comment]
Works ! Thank you !

**Comment by tjelvar-olsson** [comment]
Fix now in latest release of dtool-create: https://pypi.org/project/dtool-create/0.23.2/
